- poetry.lock
- pyproject.toml
> remove pandas dependancy

- conjugate/distributions.py
- conjugate/models.py
> Hypergeometric distribution and likelihood model

- conjugate/models.py
> Add negative binomial posterior predictive

- conjugate/distributions.py
- conjugate/models.py
> dirichlet multinomial posterior predictive

- conjugate/distributions.py
- conjugate/models.py
- tests/test_models.py
> add the posterior predictive for exponential

- conjugate/distributions.py
- conjugate/models.py
- tests/test_models.py
> add normal with known var

- conjugate/distributions.py
- conjugate/models.py
- docs/examples/sql.md
- mkdocs.yml
- pyproject.toml
- tests/test_models.py
> implement the normal model

- Makefile
- conjugate/distributions.py
- conjugate/models.py
- tests/test_distributions.py
- tests/test_models.py
Add various distributions and models
closes #68 
closes #69 
closes #70
> multivariate normal support

- conjugate/distributions.py
- conjugate/models.py
- tests/test_models.py
> log-normal posterior

- .github/workflows/coverage.yml
- .github/workflows/tests.yml
- README.md
- codecov.yml
- conjugate/_typing.py
- conjugate/plot.py
- pyproject.toml
Checking out the behavior of codecov
> Not to cover

- conjugate/models.py
> Fix `success` typo

- README.md
- conjugate/models.py
- docs/examples/binomial.md
- docs/examples/bootstrap.md
- docs/examples/linear-regression.md
- docs/examples/sql.md
- docs/index.md
- tests/test_example_plots.py
- tests/test_models.py
> Rename `<>_posterior_predictive` to `<>_predictive`

- conjugate/models.py
- tests/test_models.py
Closes #98
Introduces decorator which will do a type check
> Validate `prior` based on type hint

- conjugate/distributions.py
- conjugate/models.py
- scripts/parameter-recovery.py
- tests/test_distributions.py
- tests/test_models.py
Closes #29
Add Weibull distribution and model with known shape
Still working on the correct parameterization. The parameter recovery is not working as expected.
> Weibull known shape model

- tests/test_example_plots.py
> Address escaped character warning

- conjugate/_beta_geometric.py
- conjugate/_compound_gamma.py
- conjugate/distributions.py
- conjugate/models.py
- mkdocs.yml
- tests/test_distributions.py
- tests/test_models.py
- **implement the distribution**
- **add a docstring**
- **support for one start**
- **support for one start**
- **test support in both geometric distributions**
> Expand Geometric distribution

- conjugate/distributions.py
- conjugate/models.py
- conjugate/plot.py
> update to latest typing practices

- conjugate/models.py
- tests/test_models.py
> Normal known mean predictive alternative distribution

- conjugate/distributions.py
- conjugate/models.py
- tests/test_models.py
> Add Multivariate Normal with Unknown mu

- conjugate/distributions.py
- conjugate/models.py
- docs/examples/bayesian-update.md
- docs/examples/sql.md
- tests/test_example_plots.py
- tests/test_models.py
Closes #25
- **consolidate the logic**
- **migrate the examples**
> Normal Mean & Tau Exchangeability Model

- conjugate/models.py
- scripts/parameter-recovery.py
- **remove print statemnt**
- **check for the recovery of precision**
- **trying some different values**
> Normal Precision Parameter Recovery

- conjugate/distributions.py
- tests/test_distributions.py
> Add NormalWishart distribution

- README.md
- docs/index.md
> Add `plot_cdf` to list of features

- conjugate/models.py
- tests/test_models.py
> Fully migrate to 'prior' and 'distribution' parameters

- docs/examples/unsupported-distributions.md
- mkdocs.yml
> Add new example for Unsupport Distribution

- README.md
- docs/index.md
> Latest API in README

- .github/workflows/coverage.yml
- .github/workflows/tests.yml
> Conditional Running of tests

- .github/workflows/coverage.yml
- .github/workflows/tests.yml
- tests/test_distributions.py
> Test slice in (Beta)Geometric distribution

- Makefile
- **dummy change (#156)**
- **add a release command**
> Add release target

- .github/workflows/tests.yml
- pyproject.toml
> Add python 3.13 to test suite

- pyproject.toml
> Update the version to v0.12.0

- .github/workflows/sync-closing-labels.yml
> remove permissions of closing-issues

- .gitignore
- docs/examples/wiki-rental-car.md
- docs/examples/wiki-rental-car.py
- mkdocs.yml
- pyproject.toml
- uv.lock
- **add dependency**
- **add marimo related files**
- **add the plugin to config**
- **add the embed example**
> Add Wikipedia Example

- docs/examples/generalized-inputs.md
- pyproject.toml
- uv.lock
- **add narwhals example**
- **update depends**
> Add `narwhals` example

- docs/explorer.py
- uv.lock
Fix the plot since the formatting removed the ";"
> Fix plot after formatting'

- Makefile
- conjugate/_beta_geometric.py
- conjugate/distributions.py
- conjugate/interactive.py
- docs/explorer.py
- pyproject.toml
- tests/test_distributions.py
- uv.lock
- **add helper command**
- **remove a space;**
- **fix the domain for the beta_geometric**
- **set the min value**
- **allow for boolean flag parameters**
- **modifications to explorer**
> Improvements to Geometric distribution
